### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by kFxDaKing** [zickzackhd/lukaslogger#1]
SCRIPT ERROR: @lukaslogger/server.lua:82: attempt to concatenate a nil value (local 'result')
> ref (@lukaslogger/server.lua:82)
> (@mysql-async/mysql-async.js:15543)

**Comment by zickzackhd** [comment]
Hey wolgix, I forgot to say that you need a garage skript to manange users car lizenz or you try to tune a spannend car that has no owner both could be the error.

**Comment by kFxDaKing** [comment]
add me on discord please
kFxDaKing#7380
